### ISSUE TITLE
Handle multiple consecutive comments

### ISSUE THREAD

**Issue by hudochenkov** [hudochenkov/postcss-sorting#1]
Config: `{ "sort-order": [ ["border-bottom", "font-style"] ] }`

Input:

```css
div p em {
    /* upline comment 1 */
    /* upline comment 2 */
    font-style: italic;
    border-bottom: 1px solid red; /* trololo 1 */ /* trololo 2 */
}
```

Expected output:

```css
div p em {
    border-bottom: 1px solid red; /* trololo 1 */ /* trololo 2 */
    /* upline comment 1 */
    /* upline comment 2 */
    font-style: italic;
}
```

Current output:

```css
div p em {
    border-bottom: 1px solid red; /* trololo 1 */
    /* upline comment 2 */
    font-style: italic;
}
```
