### ISSUE TITLE
Sort by length

### ISSUE THREAD

**Issue by tomagladiator** [hudochenkov/postcss-sorting#12]
Hello,

I would like to share with you the way I sort my CSS properties:
I sort my CSS properties by length:

Wrong:
```css
.accessibility {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```

Good:
```css
.accessibility {
    clip: rect(0 0 0 0);
    position: absolute;
    overflow: hidden;
    margin: -1px;
    height: 1px;
    padding: 0;
    width: 1px;
    border: 0;
}
```

postcss-sorting should support this :+1: #

Thanks :)
