### ISSUE TITLE
An option to not change empty lines

### ISSUE THREAD

**Issue by efedorenko** [hudochenkov/postcss-sorting#20]
It would be great to have a way to completely disable `empty-lines-between-children-rules` and `empty-lines-between-media-rules`. I use empty lines to group related properties together, and right now all this organization gets removed every time I run `postcss-sorting`.

P.S. Thanks for the awesome plugin! It's a huge time saver in cleaning up a big old codebase.

**Comment by hudochenkov** [comment]
These options are disabled by default. What config do you have? What is your input CSS and what is your desired output?

**Comment by efedorenko** [comment]
I use a custom config that doesn't specify either of these rules, but a documentation says that by default they are set to `0`.

In this case, whitespace before `.weekday` was removed:

```
  .activity-timeline {
    ...

    &::before {
      ...
    }
    &::after {
      ...
    }

    .weekday {
      ...
    }
  }
```

And in that case an empty line after `@extend` was added:
```
  p:first-child {
    @extend .icon-warning;
    @extend .icon-warning--red;
    color: $c-activity-failed-txt;
  }
```

It _seems_ like only properties with pseudo-elements and pseudo-classes are affected.

**Comment by hudochenkov** [comment]
This plugin removes all empty lines and adds them after sorting process where configuration says. Empty lines added only before groups. Only by removing all empty lines plugin can be sure that additional lines not added when you run plugin over and over.

All these selectors treated equally:

```css
&::before {}
&::after {}
.weekday {}
```

The plugin doesn't know this is pseudo-element or not. It's all treated as `>child` in `sort-order`.

I will think about if I can found a way to preserve empty lines between children for a new option.

-------------------

If you have empty line between `@extend` and `color`, this mean you have config like this:

```json
{
	"sort-order": [
		[ "@atrule" ],
		[ "color" ]
	]
}
```

If you don't want empty line between atrules and properties — group them:

```json
{
	"sort-order": [
		[
			"@atrule",
			"color"
		]
	]
}
```

If you want to group properties and separate them by empty line — group them in config. See [docs about grouping](https://github.com/hudochenkov/postcss-sorting#grouping) and check [yandex preset](https://github.com/hudochenkov/postcss-sorting/blob/master/configs/yandex.json) for properties grouping example.

**Comment by efedorenko** [comment]
Oh, totally forgot about grouping. Thanks for a hint and for considering an option to preserve empty lines. It can be tolerated in a lot of places, but some of them get really annoying. For example:
```
  ...
  }

  // Changes comparing to default branch

  .branches_changes {
  ...
```

Empty lines around comment get removed.

**Comment by hudochenkov** [comment]
If you have more examples (different from what you showed before) where plugin behave not like you want, feel free to share.

**Comment by efedorenko** [comment]
After processing a project with ~450kb of SCSS I'd say that all cases when plugin removed important empty lines fall into two categories:

1. When nested selectors were grouped together by some principle (like in `.weekday`example).
2. When facing comments, both `//` and `/* ... */`.

Everything else worked exactly as intended, which is great! Just for the reference, here is my config: https://github.com/wildbit/postcss-sorting-config-wildbit/blob/master/scss-sorting.json

**Comment by hudochenkov** [comment]
I've added new option in `1.4.0`:

```
"preserve-empty-lines-between-children-rules": true
```

Tell me if something wrong :)

**Comment by efedorenko** [comment]
Thanks for a fix, Aleks! 👍 

It works as intended in most cases now, but somehow still fails a couple times on a project. It's hard to figure out why exactly, as other similar places were handled correctly. A few samples:

```scss
  .search-field-wrap {
    .search-field {
      ...

      // Remove in-field cancel button

      &::-webkit-search-cancel-button {
        appearance: none;
      }
    }
  }
```

Empty line after comment (but not before) gets removed.

```scss
      .int-card .details {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        border: 1px solid $c-int-card-brd;
        border-radius: 5px;
        box-shadow: 0 0 4px rgba(0, 0, 0, .15);

        /* Flip card animation */

        transition: all .4s ease-in-out;
        transform-style: preserve-3d;
        backface-visibility: hidden;
      }
```

Empty lines around comment get removed.

```scss
/* Invoices list */

.invoices-list {

  // Equal height for columns

  margin-bottom: -99999px;
  ...
```

Empty lines around `//` comment get removed.

**Comment by hudochenkov** [comment]
All these empty lines removed because new option preserves empty lines only _between_ children rules and comments between them. Right as you asked for :)

I have thought. Preserving empty lines is tricky because a result is unpredictable. What if I add new options: `empty-lines-before-comment` and  `empty-lines-after-comment`. This options will add empty lines before and after any comment in a rule if this comment on a separate line.

So with config like this:

```json
{
    "sort-order": [
        "..."
    ],
    "empty-lines-before-comment": 1,
    "empty-lines-after-comment": 1
}
```

On this input file:

```scss
.hello {
	display: inline-block;
	/* upline comment 1 */
	/* upline comment 2 */
	font-style: italic;
	border-bottom: 1px solid red; /* trololo 1 */ /* trololo 2 */
	/* arrow */
	&:before {
		content: "";
	}
}
```

Result will be:

```scss
.hello {
	display: inline-block;

	/* upline comment 1 */
	/* upline comment 2 */

	font-style: italic;
	border-bottom: 1px solid red; /* trololo 1 */ /* trololo 2 */

	/* arrow */

	&:before {
		content: "";
	}
}
```

But I worried about this example:

```scss
.invoices-list {

  // Equal height for columns

  margin-bottom: -99999px;
  ...
}
```

It's unusual for me to see empty line after `{`. New option `empty-lines-before-comment` won't add empty line before comment in this case. I have an idea how to hande this situation too.

```json
{
    "empty-lines-before-comment": [1, true]
}
```

If this option gets array as a value, then first element in array is number of empty lines to add, second element — add empty line if comment first thing in a rule.

What do you think about this new options? And what do you think about handling comments like in `.invoices-list`?

**Comment by efedorenko** [comment]
I wonder how this will work with different types of comments? For example:

```scss
  ...
}



/* Header
-------------------- */

.header {
  width: 100px;

  // Nasty hack
  height: 1px;
}


// Navigation

.navigation {
 ...
}
```

In this example I have 3 types of comments — a major section, an element, and a comment on some properties. All of them have different numbers of surrounding empty lines. Not sure if this is something that can be automatically managed, as it really depends on human's evaluation. What do you think?

P.S. I an not too worried about empty lines in `.invoices-list` example — at least in my code base it was a one-off thing. Managing empty lines around different types of comments is a bigger challenge.
