### ISSUE TITLE
Disable sorting for some properties at declaration-time

### ISSUE THREAD

**Issue by wc-matteo** [hudochenkov/postcss-sorting#22]
Something I would find useful, is beeing able to mark (e.g. with a comment) a point where the processor should stop sorting:

```css
.foo {
  display: inline;
  all: initial;
  /* stop sorting */
  display: block;
}
```

**Comment by hudochenkov** [comment]
I'm wondering about causes to do that. Can you explain, please, why it might be useful?

**Comment by wc-matteo** [comment]
I'm using [postcss-initial](https://github.com/maximkoretskiy/postcss-initial); by default it adds a fallback for browsers not supporting the value.

So...

```css
.foo {
  all: initial;
}
```

becomes:

```css
.foo {
  animation: none 0s ease 0s 1 normal none running;
  backface-visibility: visible;
  background: transparent none repeat 0 0 / auto auto padding-box border-box scroll;
  border: medium none currentColor;
  border-collapse: separate;
  border-image: none;
  border-radius: 0;
  border-spacing: 0;
  bottom: auto;
  box-shadow: none;
  box-sizing: content-box;
  caption-side: top;
  clear: none;
  clip: auto;
  color: #000;
  columns: auto;
  column-count: auto;
  column-fill: balance;
  column-gap: normal;
  column-rule: medium none currentColor;
  column-span: 1;
  column-width: auto;
  content: normal;
  counter-increment: none;
  counter-reset: none;
  cursor: auto;
...
  all: initial;
}
```

If I want to override some properties (in the same declaration), I can't if I use `postcss-sorting`:

```css
.foo {
  all: initial;
  display: block;
}
```

becomes:

```css
.foo {
...
  display: inline;
  display: block;
...
  all: initial;
}
```

and in browsers that support `initial`, the final value of display is `inline`, not `block`.

**Comment by hudochenkov** [comment]
This plugin is more for sorting source files. The main purpose is to have organized sources so work with them will be more convenient. Is there a reason to sort output files?

**Comment by wc-matteo** [comment]
> Is there a reason to sort output files?

To have something beautiful to show to the world (before it gets minified)? :P

Using it on source files, though:

```css
.foo {
  all: initial;

  @apply --my-initial;
}
```

I get:

```css
.foo {
  @apply --my-initial;

  all: initial;
}
```

Shouldn't _@at-rules_ not mentioned in the `sort-order` option be inserted after all the sorted _properties_?

**Comment by hudochenkov** [comment]
Can you share your config, please?

**Comment by wc-matteo** [comment]
Ah! I took my first look at the `default` config... and now it's pretty clear why! :)

**Comment by wc-matteo** [comment]
Are predefined configs extendable?

**Comment by hudochenkov** [comment]
No, they are not.

**Comment by hudochenkov** [comment]
So as we can't find any legit reason to add a feature from the starter message, I'm closing this issue.

Feel free to ask any question about config :)

**Comment by wc-matteo** [comment]
All right. Thank you!

**Comment by wc-matteo** [comment]
Thinking some more about, it would be nice to have a way to change the sorting inside the css: in this case, I'd need to add every `@apply` that I want to be sorted last to the config (or viceversa)... and it's seems to me the wrong place... maybe the same apply has to come first or last depending on context?

**Comment by hudochenkov** [comment]
Can you provide the example, please? Put `@apply` before any properties seems a bulletproof position. Because in that case you can override any content of `@apply` if you need.

**Comment by wc-matteo** [comment]
Yes, that's normally the case. But as I shown with:

```css
.foo {
  all: initial;

  @apply --my-initial;
}
```

that `@apply` should stay where it is.

**Comment by hudochenkov** [comment]
You can do crazy stuff in config :) All `@apply` will be in one place, but `@apply --my-initial` will be in another place.

Config:

```json
{
	"sort-order": [
		["@apply"],
		["display", "all"],
		["@apply --my-initial"]
	]
}
```

Before:

```css
.foo {
  all: initial;
  @apply --my-initial;
  display: block;
  @apply --hello;
}
```

After:

```css
.foo {
  @apply --hello;

  display: block;
  all: initial;

  @apply --my-initial;
}
```

**Comment by wc-matteo** [comment]
Yes, that's nice to have, but as I've said: I'd need to add every `@apply` that I want to be sorted last to the config (or viceversa)... and besides, if one `@apply --my-initial` has to go at the top and another `@apply --my-initial` has to go to the bottom? The config isn't well suited to certain scenarios...

I would propose a way to signal the beginning and stop of the sorting inside a declaration block:

```css
.foo {
  color: red;
  /* start sorting */
  font-size: 1.2em;
  text-transform: uppercase;
  /* stop sorting */
  padding: 1em;
}
```

If `start sorting` is missing, it defaults to the beginning of the declaration block; if `stop sorting` is missing, it defaults to the end of the declaration block. It should be possibile to use the command more than once per declaration block:

```css
.foo {
  /* start sorting */
  font-size: 1.2em;
  text-transform: uppercase;
  /* stop sorting */
  padding: 1em;
  /* start sorting */
  background-color: blue;
  margin: 0 0 1em;
  /* stop sorting */
}
```

Every property or at-rule outside a 'sorting block', would be left untouched.

***

As a bonus, signal to leave alone just a single property:

```css
.foo {
  font-size: 1.2em;
  color: red; /* ignore sorting */
  background-color: blue;
  margin: 0 0 1em;
}
```

akin to:

```css
.foo {
  /* start sorting */
  font-size: 1.2em;
  /* stop sorting */
  color: red;
  /* start sorting */
  background-color: blue;
  margin: 0 0 1em;
  /* stop sorting */
}
```

***

Obviously all of this could be a lot of work, for a small number of valid use cases.
