### ISSUE TITLE
Detect difference between @include foo; and @include foo { } (with content)

### ISSUE THREAD

**Issue by fliptheweb** [hudochenkov/postcss-sorting#25]
In Sass syntax I prefer to sort mixins with content to the end of the rules. For example:

``` css
.block {
  @extend %placeholder;
  @include mixin;

  position: relative;
  font-size: 15px;

  @include mixin-with-content {
    border: none;
  }
}
```

Is it rare/only my usecase?

UPD:
That link proof that's not only my case and `sass-lint` detect the same sorting https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#declarationorder
