### ISSUE TITLE
Wrong position for custom properties

### ISSUE THREAD

**Issue by hudochenkov** [hudochenkov/postcss-sorting#27]
Should be sorted as variables in order they defined.

Before:

```css
&--m2-pack {
    --width: 100px;
    --offset: 539px;
    background: #3d3d3d linear-gradient(135deg,
    // background: #3d3d3d linear-gradient(to right,
        transparent calc(var(--offset) + var(--width) * 0),
        #e9ab54 calc(var(--offset) + var(--width) * 0), #e9ab54 calc(var(--offset) + var(--width) * 1),
        #4cb5a4 calc(var(--offset) + var(--width) * 1), #4cb5a4 calc(var(--offset) + var(--width) * 2),
        #7288b9 calc(var(--offset) + var(--width) * 2), #7288b9 calc(var(--offset) + var(--width) * 3),
        #f16059 calc(var(--offset) + var(--width) * 3), #f16059 calc(var(--offset) + var(--width) * 4),
        transparent calc(var(--offset) + var(--width) * 4)
    );
    background-position: 50% 0;
    background-size: 2000px 100%;
}
```

After:

```css
&--m2-pack {
    --width: 100px;
    background: #3d3d3d linear-gradient(135deg,
    // background: #3d3d3d linear-gradient(to right,
        transparent calc(var(--offset) + var(--width) * 0),
        #e9ab54 calc(var(--offset) + var(--width) * 0), #e9ab54 calc(var(--offset) + var(--width) * 1),
        #4cb5a4 calc(var(--offset) + var(--width) * 1), #4cb5a4 calc(var(--offset) + var(--width) * 2),
        #7288b9 calc(var(--offset) + var(--width) * 2), #7288b9 calc(var(--offset) + var(--width) * 3),
        #f16059 calc(var(--offset) + var(--width) * 3), #f16059 calc(var(--offset) + var(--width) * 4),
        transparent calc(var(--offset) + var(--width) * 4)
    );
    background-position: 50% 0;
    background-size: 2000px 100%;
    --offset: 539px;
}
```
