### ISSUE TITLE
Line after dollar var

### ISSUE THREAD

**Issue by UltraDosaaf** [hudochenkov/postcss-sorting#56]
I need empty line after dollar variable. Maybe there is the option opposit to "dollar-variable-empty-line-before"?

**Comment by hudochenkov** [comment]
No there isn't. Can you show different code examples and we'll figure out what configuration you need to enforce this?

**Comment by UltraDosaaf** [comment]
Sure. Vars on top and separated with new line:
```scss
#wrapper {
   $width: 600px;
   $height: 300px;

   width: $width;
   width: $height;
   margin: 0 auto 0;

   border: 1px solid #ff0000;

   .item {
      $bg_color: #ff9900;

      background-color: $bg_color;
      position: relative;
      overflow: hidden;

      .block {
         $block_width: $width / 3;

         float: left;
         width: $block_width;
      }
   }
}
```
