### ISSUE TITLE
Bug? emptyLineBefore vs declaration-block-properties-order

### ISSUE THREAD

**Issue by vwxyutarooo** [hudochenkov/postcss-sorting#60]
I think `emptyLineBefore` can't override `declaration-block-properties-order`. Which makes dedlock each other.

`.stylelintrc`

```yaml
{
    "extends": ["stylelint-config-standard"],
    "plugins": ["stylelint-order"],
    "rules": {
        "indentation": 2,
        "number-leading-zero": null,
        "max-empty-lines": 2,
        "property-no-unknown": [ true, {
            "ignoreProperties": ["composes"]
        }],
        "order/order": [
            "custom-properties",
            "declarations"
        ],
        "order/properties-order": [
            {
                "emptyLineBefore": "never",
                "properties": [
                    "margin",
                    "padding"
                ]
            },
            {
                "emptyLineBefore": "always",
                "properties": [
                    "overflow-scrolling"
                ]
            }
        ]
    }
}
```

I supposed this shuld no errors.

```css
.test {
    padding: 10px;

    -webkit-overflow-scrolling: touch;
}
```

But this error returned actually.

`Unexpected empty line before declaration`

Then, I tried to such as following

```css
.test {
    padding: 10px;
    -webkit-overflow-scrolling: touch;
}
```

Also an error returns as following.

`Expected an empty line before propety -webkit-overflow-scrolling`

Am I misunderstood or is it Bug?
