### ISSUE TITLE
Use same properties-order logic as stylelint-order

### ISSUE THREAD

**Issue by TrevorSayre** [hudochenkov/postcss-sorting#62]
According to the [properties-order definition](https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md) for [stylelint-order](https://github.com/hudochenkov/stylelint-order):

> If an (unprefixed) property name is not included in your array and it contains a hyphen (e.g. padding-left), this rule will look for the string before that first hyphen in your array (e.g. padding) and use that position.

This creates an inconsistency with how `postcss-sorting` handles `properties-order`.

If I have the following rule:

```js
'properties-order': [
  'border',
  'color',
],
'unspecified-properties-position': 'bottom',
```

And the following css:

```css
.container {
  border: 6px solid black;
  border-right-width: 18px;
  color: red;
}
```

The css linting by `stylelint-order` will not give any warnings.

However, if I were to then run `postcss-sorting`, the `border-right-width` is moved to the bottom resulting in the following css:

```css
.container {
  border: 6px solid black;
  color: red;
  border-right-width: 18px;
}
```

Now the css linting by `stylelint-order` will give the error:

```
[stylelint] Expected "border-right-width" to come before "color" (order/properties-order)
```
