### ISSUE TITLE
Disable sorting for some at-rules

### ISSUE THREAD

**Issue by ghost** [hudochenkov/postcss-sorting#64]
How to disable sorting for some at-rules? I use the sublime text plugin and want to keep the `for`, `while` and `each` directives in the original place.

I want it to be this way:

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

  .col#{$infix},
  .col#{$infix}-auto {
    @extend %column;
  }

  @for $i from 1 through $grid-columns {
    .col#{$infix}-#{$i} {
      @extend %column;
    }
  }
}
```

**Good result:**

```css
.col,
.col-auto,
.col-1,
.col-2,
.col-3,
.col-4,
.col-5,
.col-6,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.col-sm,
.col-sm-auto,
.col-sm-1,
.col-sm-2,
.col-sm-3,
.col-sm-4,
.col-sm-5,
.col-sm-6,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
.col-md,
.col-md-auto,
.col-md-1,
.col-md-2,
.col-md-3,
.col-md-4,
.col-md-5,
.col-md-6,
.col-md-7,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
.col-lg,
.col-lg-auto,
.col-lg-1,
.col-lg-2,
.col-lg-3,
.col-lg-4,
.col-lg-5,
.col-lg-6,
.col-lg-7,
.col-lg-8,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12 {
  position: relative;
  padding-right: 1rem;
  padding-left: 1rem;
  min-height: 0.0625rem;
  width: 100%;
}
```

But when saving, it reorder as follows **(move the @for directive up and want to avoid it)**:

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

  @for $i from 1 through $grid-columns {
    .col#{$infix}-#{$i} {
      @extend %column;
    }
  }

  .col#{$infix},
  .col#{$infix}-auto {
    @extend %column;
  }
}
```

**Bad result:**

```css
.col-1,
.col-2,
.col-3,
.col-4,
.col-5,
.col-6,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.col,
.col-auto,
.col-sm-1,
.col-sm-2,
.col-sm-3,
.col-sm-4,
.col-sm-5,
.col-sm-6,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
.col-md-3,
.col-md-4,
.col-md-5,
.col-md-6,
.col-md-7,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
.col-lg-3,
.col-lg-4,
.col-lg-5,
.col-lg-6,
.col-lg-7,
.col-lg-8,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
.col-lg,
.col-lg-auto {
  position: relative;
  padding-right: 1rem;
  padding-left: 1rem;
  min-height: 0.0625rem;
  width: 100%;
}
```

This alters the order of the selectors in the resulting style sheet and want to correct it. I do not want to specify an order for these types of directives, because considering the function they fulfill, they can go in any position. I can not find a solution. Any suggestion?
