### ISSUE TITLE
Less variables order in declaration block

### ISSUE THREAD

**Issue by DarkPreacher** [hudochenkov/postcss-sorting#79]
Code example:
```less
.block {
    @c: #fff;
    color : @c;

    &--var {
        background-color: @c;
    }

    @media (min-width: 480px) {
        &-var {
            color: @c;
        }
    }
}
```

Config from VS Code:
```json
"order": [
  "custom-properties",
  "dollar-variables",
  "declarations",
  "rules",
  "at-rules"
]
```

Expected output — like in example, got:
```less
.block {
    color : @c;

    &--var {
        background-color: @c;
    }

    @media (min-width: 480px) {
        &-var {
            color: @c;
        }
    }
    @c: #fff;
}
```

Less is able to produce valid css out of this, but it looks awkward I think.
Maybe there is some config to fix it?
