### ISSUE TITLE
Pseudo elements sorting

### ISSUE THREAD

**Issue by evgenTraytyak** [hudochenkov/postcss-sorting#8]
@hudochenkov What do you think about sorting nested pseudo elements?
```scss
.block {
    width: 100px;
    height: 100px;
    display: block;
    background-color: red;

    &::before {
        width: 20px;
        height: 20px;
    }

    &::after {
        width: 20px;
        height: 20px;
    }
}
```

```scss
.paragraph {
    font-size: 16px;
    line-height: 1.2;
    color: 333;

    &::first-letter {
        font-size: 24px;
    }

    &::first-letter {
        color: black;
    }

    &::selection {
        color: yellow;
        background: #333;
    }
}
```

**Comment by evgenTraytyak** [comment]
```json
"sort-order": [
    [
        "display",
        //some properties
    ],
    [
        "::before",
        "::after",
        "::first-letter",
        "::first-letter",
        "::selection",

    ]
]
```

**Comment by hudochenkov** [comment]
Do you think this is really need? What if selector is `&::before, &::after` or `&::after, &::before` or `&:hover::after`? I don't think this kind of sorting is needed. Implementing this will bring much mess in plugin and may mess with CSS a lot in case of tricky selector.

**Comment by evgenTraytyak** [comment]
Yes, it's really need.
Assume some dirty code like this:
```scss
.block {
    width: 100px;
    height: 100px;
    display: block;
    background-color: red;

    &::after {
        width: 20px;
        height: 20px;
    }

    border: 1px solid blue; 

    &__element {
        padding: 10px; 
    }

    &::before {
        width: 20px;
        height: 20px;
    }

    opacity: 0.9; 

    @extend .clearfix;
}
```

And I want to put pseudo elements properties  at the beginning of `.block` , then nested elements.

```scss
.block {
    @extend .clearfix;
    
    width: 100px;
    height: 100px;
    display: block;
    background-color: red;

    border: 1px solid blue; 
    opacity: 0.9; 
    
    &::after {
        width: 20px;
        height: 20px;
    }

    &::before {
        width: 20px;
        height: 20px;
    }

    &__element {
        padding: 10px; 
    }
}
```
