### ISSUE TITLE
Compine at rules with properties in sorting

### ISSUE THREAD

**Issue by Unknow-max** [hudochenkov/postcss-sorting#89]
Hi everyone,
In my sass workflow I use a lot of mixins (positioning, shapes, flexbox ecc). I would like instead of put these mixins above or under my properties to combine them together. 
I will try to explain better.
Take this code: 

```scss
 .value {
    padding: 3.5rem;
    @include relative(top 0);
    transition-property: transform, opacity, top !important;
@include flexbox-layout(items-center, justify-center, grow-1);
  }
```

Running postcss sorting will result:
```scss
 .value {
@include flexbox-layout(items-center, justify-center, grow-1);
    @include relative(top 0);
    padding: 3.5rem;
    transition-property: transform, opacity, top !important;
  }
```
Instead, I would like to combine the order of these at-rules and properties, something like this:
```scss
 .value {
@include flexbox-layout(items-center, justify-center, grow-1);
    padding: 3.5rem;
@include relative(top 0);
    transition-property: transform, opacity, top !important;
  }
```

Is this possible to implement?
